version: "3.8"

x-app-volumes: &app-volumes
  volumes:
    - ./public:/usr/app/public:delegated
    - ./src:/usr/app/src:delegated
    - ./tests:/usr/app/tests:delegated
    - ./composer.json:/usr/app/composer.json:delegated
    - ./composer.lock:/usr/app/composer.lock:delegated
    - ./phpunit.xml.dist:/usr/app/phpunit.xml.dist:delegated
    - app-vendor:/usr/app/vendor

volumes:
  app-vendor:

networks:
  app:

services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: em-app
    command: ["tail", "-f", "/dev/null"]
    networks:
      - app
    <<: *app-volumes
